### ISSUE TITLE
Options with $ on field declaration

### ISSUE THREAD

**Issue by chatzisnik** [froala/nova-froala-field#43]
Hi,

I am trying to change the enter key behaviour on my Field in nova, 
On the documentation it is stated that we should use:
```
'enter'=> '$.FroalaEditor.ENTER_DIV',
```
on the options of the field, which in my case doesn't work and messes up my inputs with <undefined> tags. 

What is the right way to use options like that?

**Comment by slavarazum** [comment]
Looks like currently it's not possible, because `$.FroalaEditor.ENTER_DIV` is JavaScript expression, other options is just scalar types. We can't set javascript expressions in php configs.
I think you can send a suggestion to https://github.com/froala/wysiwyg-editor repository with a suggestion to improve it.
